name: google_map_animation
description: "A Flutter library for creating animated polylines and markers on Google Maps with smooth transitions and customizable effects."


version: 1.0.0

repository: https://github.com/manishrelani/google_map_animation
documentation: https://github.com/yourusername/google_map_animation/blob/main/README.md

environment:
  sdk: ^3.8.1
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.12.3
  google_maps_flutter_platform_interface: ^2.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

# Add topics for better discoverability
topics:
  - google-maps
  - animation
  - polyline
  - flutter
  - maps



















